services:
  moodle:
    build: .
    container_name: moodle-app
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html
      - /home/ubuntu/moodledata:/var/www/moodledata
    depends_on:
      - db
    environment:
      MOODLE_DOCKER_DBTYPE: mariadb
      MOODLE_DOCKER_DBHOST: db
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodleuser
      MOODLE_DOCKER_DBPASS: moodleuser

  db:
    image: mariadb:10.6
    container_name: moodle-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodleuser
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
